name: 步步宝3	

on:	
  workflow_dispatch:	
  schedule:	
    - cron: '0 */4 * * *'	
  watch:	
    types: started	
  repository_dispatch:	
    types: BBB.js	
jobs:	
  build:	

    runs-on: ubuntu-latest	
    if: github.event.repository.owner.id == github.event.sender.id
    env:	
          BBB_CK: ${{ secrets.BBB_CK3 }} 
          TZ: Asia/shanghai			
    steps:	
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Use Node.js 12.x	
        uses: actions/setup-node@v1	
        with:	
          node-version: 12.x	
      - name: npm install	
        run: |	
          npm install	
      - name: '运行 【步步宝账户3】'	
        run: |	
          node BBB212.js	
        env:		
          JD_DEBUG: ${{ secrets.JD_DEBUG }}	
          PUSH_KEY: ${{ secrets.PUSH_KEY }}	
          BARK_PUSH: ${{ secrets.BARK_PUSH }}	
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}	
          TG_USER_ID: ${{ secrets.TG_USER_ID }}	
          BARK_SOUND: ${{ secrets.BARK_SOUND }}	
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}	
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}	
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
